apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: composed-providerconfig
  annotations:
    gotemplate.xfn.upbound.io/resource-name: "resource-provider-config"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: cluster-config
      key: kubeconfig
---
apiVersion: meta.gotemplate.xfn.upbound.io/v1alpha1
kind: ReadinessChecks
metadata:
  name: resource-provider-config
readinessChecks:
- type: None
