{{- if .composite.resource.spec.parameters.createSecret }}
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: "i-am-the-secret"
  annotations:
    gotemplate.xfn.upbound.io/resource-name: "resource-the-secret"
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: sample-namespace
        labels:
          example: "true"
      stringData:
        secret: "yes"
---
{{- end }}